/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

/**
 *
 * @author barba
 */
public class IMCTela extends javax.swing.JFrame {

    /**
     * Creates new form Tela2
     */
    public IMCTela() {
        initComponents();
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelGeral = new javax.swing.JPanel();
        PainelAlturaPeso = new javax.swing.JPanel();
        Altura = new javax.swing.JLabel();
        Peso = new javax.swing.JLabel();
        CaixaAltura = new javax.swing.JTextField();
        CaixaPeso = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        PainelResultado = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextoBoasVindas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Altura.setText("ALTURA (m):");

        Peso.setText("PESO (KG):");

        CaixaAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaAlturaActionPerformed(evt);
            }
        });

        Calcular.setText("CALCULAR");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        Voltar.setText("VOLTAR");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelAlturaPesoLayout = new javax.swing.GroupLayout(PainelAlturaPeso);
        PainelAlturaPeso.setLayout(PainelAlturaPesoLayout);
        PainelAlturaPesoLayout.setHorizontalGroup(
            PainelAlturaPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAlturaPesoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(PainelAlturaPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Altura)
                    .addComponent(Peso))
                .addGap(34, 34, 34)
                .addGroup(PainelAlturaPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CaixaAltura)
                    .addComponent(CaixaPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelAlturaPesoLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        PainelAlturaPesoLayout.setVerticalGroup(
            PainelAlturaPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAlturaPesoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PainelAlturaPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Altura)
                    .addComponent(CaixaAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAlturaPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Peso)
                    .addComponent(CaixaPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PainelAlturaPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calcular)
                    .addComponent(Voltar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel4.setText("RESULTADO:");

        jLabel5.setText("INTERPRETAÇÃO:");

        javax.swing.GroupLayout PainelResultadoLayout = new javax.swing.GroupLayout(PainelResultado);
        PainelResultado.setLayout(PainelResultadoLayout);
        PainelResultadoLayout.setHorizontalGroup(
            PainelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelResultadoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PainelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        PainelResultadoLayout.setVerticalGroup(
            PainelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelResultadoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        TextoBoasVindas.setBackground(new java.awt.Color(255, 102, 204));
        TextoBoasVindas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TextoBoasVindas.setText("Calculo de IMC");

        javax.swing.GroupLayout PainelGeralLayout = new javax.swing.GroupLayout(PainelGeral);
        PainelGeral.setLayout(PainelGeralLayout);
        PainelGeralLayout.setHorizontalGroup(
            PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelGeralLayout.createSequentialGroup()
                .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelGeralLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PainelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PainelAlturaPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelGeralLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(TextoBoasVindas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelGeralLayout.setVerticalGroup(
            PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelGeralLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(TextoBoasVindas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelAlturaPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(PainelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CaixaAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaAlturaActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
      dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_VoltarActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // Coletar dados informados
    try {
        double altura = Double.parseDouble(CaixaAltura.getText());
        double peso = Double.parseDouble(CaixaPeso.getText());

        // Validar se todos os campos foram preenchidos
        if (altura <= 0 || peso <= 0) {
            throw new IllegalArgumentException("Altura e peso devem ser valores positivos.");
        }

        // Calcular o IMC
        double imc = peso / (altura * altura);

        // Exibir o resultado
        jLabel4.setText("RESULTADO: " + String.format("%.2f", imc));

        // Determinar a interpretação
        String interpretacao = "";
        if (imc < 18.5) {
            interpretacao = "Magreza";
        } else if (imc >= 18.5 && imc <= 24.9) {
            interpretacao = "Normal";
        } else if (imc >= 25 && imc <= 29.9) {
            interpretacao = "Sobrepeso";
        } else if (imc >= 30 && imc <= 39.9) {
            interpretacao = "Obesidade";
        } else {
            interpretacao = "Obesidade grave";
        }

        // Exibir a interpretação
        jLabel5.setText("INTERPRETAÇÃO: " + interpretacao);

    } catch (NumberFormatException e) {
        // Lidar com exceção se os campos não contêm números
        jLabel4.setText("RESULTADO: Preencha todos os campos com valores válidos.");
        jLabel5.setText("INTERPRETAÇÃO: ");
    } catch (IllegalArgumentException e) {
        // Lidar com exceção se valores negativos ou zero foram fornecidos
        jLabel4.setText("RESULTADO: " + e.getMessage());
        jLabel5.setText("INTERPRETAÇÃO: ");
    }
    }//GEN-LAST:event_CalcularActionPerformed
     
         

/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IMCTela().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Altura;
    private javax.swing.JTextField CaixaAltura;
    private javax.swing.JTextField CaixaPeso;
    private javax.swing.JButton Calcular;
    private javax.swing.JPanel PainelAlturaPeso;
    private javax.swing.JPanel PainelGeral;
    private javax.swing.JPanel PainelResultado;
    private javax.swing.JLabel Peso;
    private javax.swing.JLabel TextoBoasVindas;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
