/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

/**
 *
 * @author barba
 */

public class TelaRecomendacoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaRecomendacoes
     */
    public TelaRecomendacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelGeral = new javax.swing.JPanel();
        TituloRecomendacoes = new javax.swing.JLabel();
        PainelCalorias = new javax.swing.JPanel();
        TextoCalorias = new javax.swing.JLabel();
        EspacoCalorias = new javax.swing.JTextField();
        BotaoCalcular = new javax.swing.JButton();
        BotaoVoltar = new javax.swing.JButton();
        PainelInferior = new javax.swing.JPanel();
        Carboidrato = new javax.swing.JLabel();
        Proteina = new javax.swing.JLabel();
        Gordura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloRecomendacoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TituloRecomendacoes.setText("RECOMENDAÇÕES");

        TextoCalorias.setText("CALORIAS DIARIAS (KCAL) :");

        EspacoCalorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacoCaloriasActionPerformed(evt);
            }
        });

        BotaoCalcular.setText("CALCULAR");
        BotaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCalcularActionPerformed(evt);
            }
        });

        BotaoVoltar.setText("VOLTAR");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelCaloriasLayout = new javax.swing.GroupLayout(PainelCalorias);
        PainelCalorias.setLayout(PainelCaloriasLayout);
        PainelCaloriasLayout.setHorizontalGroup(
            PainelCaloriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCaloriasLayout.createSequentialGroup()
                .addGroup(PainelCaloriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCaloriasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TextoCalorias)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCaloriasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(PainelCaloriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EspacoCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelCaloriasLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(BotaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        PainelCaloriasLayout.setVerticalGroup(
            PainelCaloriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCaloriasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PainelCaloriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EspacoCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PainelCaloriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Carboidrato.setText("CARBOIDRATO (50%):");

        Proteina.setText("PROTEÍNA (25%):");

        Gordura.setText("GORDURA (25%):");

        javax.swing.GroupLayout PainelInferiorLayout = new javax.swing.GroupLayout(PainelInferior);
        PainelInferior.setLayout(PainelInferiorLayout);
        PainelInferiorLayout.setHorizontalGroup(
            PainelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInferiorLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(PainelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gordura)
                    .addComponent(Proteina)
                    .addComponent(Carboidrato))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        PainelInferiorLayout.setVerticalGroup(
            PainelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelInferiorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Carboidrato)
                .addGap(18, 18, 18)
                .addComponent(Proteina)
                .addGap(18, 18, 18)
                .addComponent(Gordura)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelGeralLayout = new javax.swing.GroupLayout(PainelGeral);
        PainelGeral.setLayout(PainelGeralLayout);
        PainelGeralLayout.setHorizontalGroup(
            PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelGeralLayout.createSequentialGroup()
                .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PainelCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelGeralLayout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addComponent(TituloRecomendacoes))
                        .addGroup(PainelGeralLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(PainelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PainelGeralLayout.setVerticalGroup(
            PainelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloRecomendacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(PainelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EspacoCaloriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacoCaloriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacoCaloriasActionPerformed

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void BotaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCalcularActionPerformed
        try {
        // Coletar calorias informadas
        double calorias = Double.parseDouble(EspacoCalorias.getText());

        // Calcular quantidade recomendada dos nutrientes
        double carboidratos = calorias * 0.5 / 4;
        double proteinas = calorias * 0.25 / 4;
        double gordura = calorias * 0.25 / 9;

        // Exibir os resultados
        Carboidrato.setText("CARBOIDRATO (50%): " + String.format("%.2f g", carboidratos));
        Proteina.setText("PROTEÍNA (25%): " + String.format("%.2f g", proteinas));
        Gordura.setText("GORDURA (25%): " + String.format("%.2f g", gordura));

    } catch (NumberFormatException e) {
        // Lidar com exceção se os campos não contêm números
        Carboidrato.setText("CARBOIDRATO (50%): Preencha com um valor válido.");
        Proteina.setText("PROTEÍNA (25%): Preencha com um valor válido.");
        Gordura.setText("GORDURA (25%): Preencha com um valor válido.");
    }

    }//GEN-LAST:event_BotaoCalcularActionPerformed

    
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaRecomendacoes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCalcular;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JLabel Carboidrato;
    private javax.swing.JTextField EspacoCalorias;
    private javax.swing.JLabel Gordura;
    private javax.swing.JPanel PainelCalorias;
    private javax.swing.JPanel PainelGeral;
    private javax.swing.JPanel PainelInferior;
    private javax.swing.JLabel Proteina;
    private javax.swing.JLabel TextoCalorias;
    private javax.swing.JLabel TituloRecomendacoes;
    // End of variables declaration//GEN-END:variables
}
