/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

/**
 *
 * @author barba
 */
public class TelaInnicial extends javax.swing.JFrame {

    /**
     * Creates new form Tela1
     */
    public TelaInnicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaTotal = new javax.swing.JPanel();
        IMC = new javax.swing.JButton();
        GastoCalorico = new javax.swing.JButton();
        Recomendacoes = new javax.swing.JButton();
        TextoBoasVindas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IMC.setText("IMC");
        IMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMCActionPerformed(evt);
            }
        });

        GastoCalorico.setText("GASTO CALORICO");
        GastoCalorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GastoCaloricoActionPerformed(evt);
            }
        });

        Recomendacoes.setText("RECOMENDAÇÕES");
        Recomendacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecomendacoesActionPerformed(evt);
            }
        });

        TextoBoasVindas.setBackground(new java.awt.Color(255, 102, 204));
        TextoBoasVindas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TextoBoasVindas.setText("Bem vindo! Selecione uma opção:");

        javax.swing.GroupLayout AreaTotalLayout = new javax.swing.GroupLayout(AreaTotal);
        AreaTotal.setLayout(AreaTotalLayout);
        AreaTotalLayout.setHorizontalGroup(
            AreaTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaTotalLayout.createSequentialGroup()
                .addGroup(AreaTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AreaTotalLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(TextoBoasVindas))
                    .addGroup(AreaTotalLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(AreaTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GastoCalorico, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IMC, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Recomendacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        AreaTotalLayout.setVerticalGroup(
            AreaTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextoBoasVindas)
                .addGap(34, 34, 34)
                .addComponent(IMC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(GastoCalorico, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Recomendacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMCActionPerformed
     IMCTela tela = new IMCTela ();
     tela.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_IMCActionPerformed

    private void GastoCaloricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GastoCaloricoActionPerformed
      TelaGastoCalorico tela = new TelaGastoCalorico () ;
      tela.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_GastoCaloricoActionPerformed

    private void RecomendacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecomendacoesActionPerformed
     TelaRecomendacoes tela = new TelaRecomendacoes ();
     tela.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_RecomendacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInnicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInnicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInnicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInnicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInnicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AreaTotal;
    private javax.swing.JButton GastoCalorico;
    private javax.swing.JButton IMC;
    private javax.swing.JButton Recomendacoes;
    private javax.swing.JLabel TextoBoasVindas;
    // End of variables declaration//GEN-END:variables
}
