/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

/**
 *
 * @author barba
 */
public class TelaGastoCalorico extends javax.swing.JFrame {

    /**
     * Creates new form Tela3
     */
    public TelaGastoCalorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TituloGastoCalorico = new javax.swing.JLabel();
        TextoPeso = new javax.swing.JLabel();
        TextoAltura = new javax.swing.JLabel();
        TextoIdade = new javax.swing.JLabel();
        TextoAtividade = new javax.swing.JLabel();
        BotaoCalcular = new javax.swing.JButton();
        EspacoPeso = new javax.swing.JTextField();
        EspacoAltura = new javax.swing.JTextField();
        EspacoIdade = new javax.swing.JTextField();
        EspacoAtividade = new javax.swing.JComboBox<>();
        GastoBasal = new javax.swing.JLabel();
        GastoTotal = new javax.swing.JLabel();
        BotaoVoltar = new javax.swing.JButton();
        OpcaoMulher = new javax.swing.JRadioButton();
        OpcaoHomem = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloGastoCalorico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TituloGastoCalorico.setText("CALCULO DE GASTO CALORICO");

        TextoPeso.setText("PESO(KG) :");

        TextoAltura.setText("ALTURA (m):");

        TextoIdade.setText("IDADE :");

        TextoAtividade.setText("NIVEL DE ATIVIDADE:");

        BotaoCalcular.setText("CALCULAR");
        BotaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCalcularActionPerformed(evt);
            }
        });

        EspacoPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacoPesoActionPerformed(evt);
            }
        });

        EspacoAtividade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma Opção", "Sedentario", "Leve (exercício leve 1 a 3 dias/semana)", "Moderado (exercício moderado 3 a 5 dias/semana)", "Ativo (exercício pesado 5 a 6 dias/semana)", "Extremamente ativo (exercício pesado diário)" }));
        EspacoAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacoAtividadeActionPerformed(evt);
            }
        });

        GastoBasal.setText("GASTO BASAL:");

        GastoTotal.setText("GASTO TOTAL:");

        BotaoVoltar.setText("VOLTAR");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        GrupoSexo.add(OpcaoMulher);
        OpcaoMulher.setText("MULHER");
        OpcaoMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcaoMulherActionPerformed(evt);
            }
        });

        GrupoSexo.add(OpcaoHomem);
        OpcaoHomem.setText("HOMEM");
        OpcaoHomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcaoHomemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TituloGastoCalorico)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OpcaoHomem)
                        .addGap(87, 87, 87)
                        .addComponent(OpcaoMulher)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GastoBasal)
                    .addComponent(GastoTotal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoAtividade)
                            .addComponent(TextoAltura)
                            .addComponent(TextoPeso)
                            .addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EspacoAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(BotaoCalcular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EspacoIdade)
                            .addComponent(EspacoPeso))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(EspacoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(TituloGastoCalorico)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpcaoHomem)
                    .addComponent(OpcaoMulher))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EspacoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoPeso))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoAltura)
                    .addComponent(EspacoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EspacoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EspacoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoAtividade))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(GastoBasal)
                .addGap(30, 30, 30)
                .addComponent(GastoTotal)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EspacoPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacoPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacoPesoActionPerformed

    private void EspacoAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacoAtividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacoAtividadeActionPerformed

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void OpcaoMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcaoMulherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcaoMulherActionPerformed

    private void OpcaoHomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcaoHomemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcaoHomemActionPerformed

    private void BotaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCalcularActionPerformed
          try {
        // Coletar dados informados
        double peso = Double.parseDouble(EspacoPeso.getText());
        double altura = Double.parseDouble(EspacoAltura.getText());
        int idade = Integer.parseInt(EspacoIdade.getText());

        // Validar se todos os campos foram preenchidos
        if (peso <= 0 || altura <= 0 || idade <= 0) {
            throw new IllegalArgumentException("Preencha todos os campos com valores válidos.");
        }

        // Calcular gasto calórico basal
        double calBasal = 0;
        if (OpcaoHomem.isSelected()) {
            calBasal = 66 + (13.8 * peso) + (5 * altura) - (6.8 * idade);
        } else if (OpcaoMulher.isSelected()) {
            calBasal = 655 + (9.6 * peso) + (1.9 * altura) - (4.7 * idade);
        }

        // Exibir o gasto calórico basal
        GastoBasal.setText("GASTO BASAL: " + String.format("%.2f", calBasal));

        // Calcular gasto calórico total com base no nível de atividade
        double calTotal = 0;
        String nivelAtividade = (String) EspacoAtividade.getSelectedItem();
        switch (nivelAtividade) {
            case "Sedentario":
                calTotal = calBasal * 1.2;
                break;
            case "Leve (exercício leve 1 a 3 dias/semana)":
                calTotal = calBasal * 1.375;
                break;
            case "Moderado (exercício moderado 3 a 5 dias/semana)":
                calTotal = calBasal * 1.55;
                break;
            case "Ativo (exercício pesado 5 a 6 dias/semana)":
                calTotal = calBasal * 1.725;
                break;
            case "Extremamente ativo (exercício pesado diário)":
                calTotal = calBasal * 1.9;
                break;
            default:
                break;
        }

        // Exibir o gasto calórico total
        GastoTotal.setText("GASTO TOTAL: " + String.format("%.2f", calTotal));

    } catch (NumberFormatException e) {
        // Lidar com exceção se os campos não contêm números
        GastoBasal.setText("GASTO BASAL: Preencha todos os campos com valores válidos.");
        GastoTotal.setText("GASTO TOTAL: ");
    } catch (IllegalArgumentException e) {
        // Lidar com exceção se valores inválidos ou campos em branco forem fornecidos
        GastoBasal.setText("GASTO BASAL: " + e.getMessage());
        GastoTotal.setText("GASTO TOTAL: ");
    }
    }//GEN-LAST:event_BotaoCalcularActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaGastoCalorico().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCalcular;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JTextField EspacoAltura;
    private javax.swing.JComboBox<String> EspacoAtividade;
    private javax.swing.JTextField EspacoIdade;
    private javax.swing.JTextField EspacoPeso;
    private javax.swing.JLabel GastoBasal;
    private javax.swing.JLabel GastoTotal;
    private javax.swing.ButtonGroup GrupoSexo;
    private javax.swing.JRadioButton OpcaoHomem;
    private javax.swing.JRadioButton OpcaoMulher;
    private javax.swing.JLabel TextoAltura;
    private javax.swing.JLabel TextoAtividade;
    private javax.swing.JLabel TextoIdade;
    private javax.swing.JLabel TextoPeso;
    private javax.swing.JLabel TituloGastoCalorico;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
